name: Deploy Docs Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install make
          python setup.py RANDOM_PROJECT_OOOOO 1.1.Anything cool_lammas
          python -m venv sdocs
          source sdocs/bin/activate
          python -m pip install -r docs.requirements.txt
          python -m pip install -r requirements.txt
          rm setup.py

      - name: Build Documentation
        run: |
          source sdocs/bin/activate
          cd docs
          make html
          cd build/html
          echo "I dislike Github Pages" >> .nojekyll
      - name: Deploy Documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./docs/build/html # The folder the action should deploy.
